### ISSUE TITLE
Sending raw IPv6 frames

### ISSUE THREAD

**Issue by dns2utf8** [coldFireworks/packet_crafter#2]
Hi @coldFireworks 

I am building a small utility where I send ICMP RA frames.
It looks like there is no `Ipv6Header` struct and `headers::IpHeader` is v4 only?

Is this correct?

Cheers,
Stefan

**Comment by coldFireworks** [comment]
Hi Stefan,

This tool was built to be used in a personal project of mine, and I didn't require ipv6 support for that, which is why I never bothered to build it.
I'm glad you have found my tool here and decided to contribute, I've now merged your changes in so ipv6 packets can be made, and therefore I will close this issue.

Thanks again for your contribution!
